In [17]:
from transformers import TFAlbertForSequenceClassification
from transformers import BertTokenizerFast
import tensorflow as tf
import numpy as np


In [3]:
# 파인튜닝된 모델을 가중치와 함께 불러온다.
loaded_model = TFAlbertForSequenceClassification.from_pretrained('./emo_finetuned_albert-kor-base')

All model checkpoint layers were used when initializing TFAlbertForSequenceClassification.

All the layers of TFAlbertForSequenceClassification were initialized from the model checkpoint at ./emo_finetuned_albert-kor-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFAlbertForSequenceClassification for predictions without further training.


In [20]:
example_texts = ['넌 별로지만 좋기도해','너무 안좋다..',';;;; ...','대박이네','좋을지도?']

# 토큰화진행 
tokenizer = BertTokenizerFast.from_pretrained("kykim/albert-kor-base")
#토큰화된 문장의길이는 임의로 64지정
test_encodings = tokenizer(example_texts, truncation=True, padding='max_length', max_length=64,return_token_type_ids= False) 

# 새로운 데이터를 입력 데이터로 변환
test_input_ids = np.array(test_encodings['input_ids'])
test_attention_mask = np.array(test_encodings['attention_mask'])


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'AlbertTokenizerFast'. 
The class this function is called from is 'BertTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'AlbertTokenizerFast'. 
The class this function is called from is 'BertTokenizerFast'.


In [21]:
#데이터확인
n=4
#수치형 데이터
print(test_encodings['input_ids'][n])
#토큰화된 텍스트
print(tokenizer.convert_ids_to_tokens(test_encodings['input_ids'][n]))
#원본텍스트
print(tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(test_encodings['input_ids'][n])))

[2, 39712, 8144, 2033, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['[CLS]', '좋을지', '##도', '?', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
[CLS] 좋을지도? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] 

In [22]:
predicted = loaded_model.predict([test_input_ids, test_attention_mask])
predicted[0][0]

1/1 [==============================] - 1s 960ms/step


array([-0.7469093,  3.6134062, -1.0537384, -1.2189223, -0.4793804],
      dtype=float32)

In [34]:
for i in predicted[0]:
    probabilities = tf.nn.softmax(i)
    print(probabilities)
    print(np.round(probabilities).astype(int))


tf.Tensor([0.01220285 0.9552613  0.00897857 0.00761147 0.01594584], shape=(5,), dtype=float32)
[0 1 0 0 0]
tf.Tensor([9.9923503e-01 3.6839326e-04 1.4503566e-04 8.2970095e-05 1.6857049e-04], shape=(5,), dtype=float32)
[1 0 0 0 0]
tf.Tensor([2.0364339e-04 9.9921119e-01 2.8810793e-04 1.6516287e-04 1.3183978e-04], shape=(5,), dtype=float32)
[0 1 0 0 0]
tf.Tensor([0.00126993 0.0016664  0.00704778 0.62186646 0.36814937], shape=(5,), dtype=float32)
[0 0 0 1 0]
tf.Tensor([1.1093362e-04 1.5350366e-03 6.8980968e-03 9.9043989e-01 1.0160032e-03], shape=(5,), dtype=float32)
[0 0 0 1 0]
