메켑연습

In [1]:
# !pip install konlpy

In [2]:
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
import tensorflow as tf
import numpy as np

#1. Naver Sentiment Movie Corpus v1.0 다운로드
train_file = tf.keras.utils.get_file('train.txt', 'https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt')
# test_file = tf.keras.utils.get_file( 'test.txt',  'https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt')

#파일을 이진모드로 읽어온다. 디코드는 utf8로한다.
train_text = open(train_file,'rb').read().decode(encoding='utf-8')
# test_text = open(test_file,'rb').read().decode(encoding='utf-8')


In [3]:
import pandas as pd

df_train = pd.DataFrame({
    'feature':[row.split('\t')[1] for row in train_text.split('\n')[1:] if row.count('\t')>0],
    'target': [ int(row.split('\t')[2]) for row in train_text.split('\n')[1:] if row.count('\t')>0]
})

#데이터 크기 지정
df_train = df_train[::6]

In [4]:
#문장 추출
texts= [ ]
for i in df_train['feature']:
    texts.append(i)
len(texts)

25000

In [5]:
#문자열이 아닌게 있는지 확인
for i in texts:
    if type(i)!=str:
        print(i)

In [6]:
# train 데이터 입력값(X)을 정제(Cleaning)
import re
from soynlp.normalizer import repeat_normalize

def clean_korean_text(text):
    # 특수 문자 및 숫자 제거
    text = re.sub(r'[^가-힣ㄱ-ㅎㅏ-ㅣ\s]', '', text)
    # 반복되는 자음, 모음 제거 (e.g., 'ㅋㅋㅋ' -> 'ㅋ')
    text = repeat_normalize(text, num_repeats=1)
    # 띄어쓰기 정규화 (연속된 공백 문자를 하나의 공백 문자로 변환)
    text = re.sub(r'\s+', ' ', text).strip()
    #정제할것 추가. => 고도화

    return text

clean_texts=[]
for i in texts:
    clean_texts.append(clean_korean_text(i))

In [7]:
# len(clean_texts)
clean_texts[:5]

['아 더빙 진짜 짜증나네요 목소리',
 '원작의 긴장감을 제대로 살려내지못했다',
 '울면서 손들고 횡단보도 건널때 뛰쳐나올뻔 이범수 연기 드럽게못해',
 '이건 정말 깨알 캐스팅과 질퍽하지않은 산뜻한 내용구성이 잘 버무러진 깨알일드',
 '주제는 좋은데 중반부터 지루하다']

In [8]:
#불용어사전 가져와서 리스트로 만들기
stop_words = open('./stopwords.txt','rb').read().decode(encoding='utf-8')

#리스트 컴프리헨션
stop_words = [ i for i in stop_words.split('\n') ]
stop_words

['가',
 '가까스로',
 '가령',
 '각',
 '각각',
 '각자',
 '각종',
 '갖고말하자면',
 '같다',
 '같이',
 '개의치않고',
 '거니와',
 '거바',
 '거의',
 '것',
 '것과 같이',
 '것들',
 '게다가',
 '게우다',
 '겨우',
 '견지에서',
 '결과에 이르다',
 '결국',
 '결론을 낼 수 있다',
 '겸사겸사',
 '고려하면',
 '고로',
 '곧',
 '공동으로',
 '과',
 '과연',
 '관계가 있다',
 '관계없이',
 '관련이 있다',
 '관하여',
 '관한',
 '관해서는',
 '구',
 '구체적으로',
 '구토하다',
 '그',
 '그들',
 '그때',
 '그래',
 '그래도',
 '그래서',
 '그러나',
 '그러니',
 '그러니까',
 '그러면',
 '그러므로',
 '그러한즉',
 '그런 까닭에',
 '그런데',
 '그런즉',
 '그럼',
 '그럼에도 불구하고',
 '그렇게 함으로써',
 '그렇지',
 '그렇지 않다면',
 '그렇지 않으면',
 '그렇지만',
 '그렇지않으면',
 '그리고',
 '그리하여',
 '그만이다',
 '그에 따르는',
 '그위에',
 '그저',
 '그중에서',
 '그치지 않다',
 '근거로',
 '근거하여',
 '기대여',
 '기점으로',
 '기준으로',
 '기타',
 '까닭으로',
 '까악',
 '까지',
 '까지 미치다',
 '까지도',
 '꽈당',
 '끙끙',
 '끼익',
 '나',
 '나머지는',
 '남들',
 '남짓',
 '너',
 '너희',
 '너희들',
 '네',
 '넷',
 '년',
 '논하지 않다',
 '놀라다',
 '누가 알겠는가',
 '누구',
 '다른',
 '다른 방면으로',
 '다만',
 '다섯',
 '다소',
 '다수',
 '다시 말하자면',
 '다시말하면',
 '다음',
 '다음에',
 '다음으로',
 '단지',
 '답다',
 '당신',
 '당장',
 '대로 하다',
 '대하면',
 '대하여',
 '대해 말하자면',
 '대해서',
 '댕그',


In [9]:
# class A:=> 클래스에 함수가 들어가면 == 메서드

In [10]:
#tfidf하면서 토큰화는 okt.morphs로 한다.=> 매켑으로해본다.
from sklearn.feature_extraction.text import TfidfVectorizer
from konlpy.tag import Mecab
import pickle

#vectorizer객체를 저장하기위해 사용자지정 함수생성
#메켑 함수 선언
def mecab_tokenizer(text):
    mecab = Mecab()
    return mecab.morphs(text)

#문장을 쪼개는 토큰화  +  불용어 제거(은는이가)  + 수치형으로 바꾸는 벡터화 동시에   
vectorizer = TfidfVectorizer( tokenizer = mecab_tokenizer, stop_words = stop_words )

X_train = vectorizer.fit_transform( clean_texts )

# vectorizer 객체(=클래스)를 저장합니다.
with open('mecab_test_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)
    

#만약 테스트문장 똑같은 벡터화과정을 거쳐야한다.
# vectorizer.transform( X_test )
# y = df_train.iloc[:,1]

c:\Users\uk246\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Exception: Install MeCab in order to use it: http://konlpy.org/en/latest/install/

In [ ]:
import pickle

# 저장된 vectorizer 객체를 불러옵니다.
with open('test_vectorizer.pkl', 'rb') as f:
    loaded_test_vectorizer = pickle.load(f)

In [ ]:
test_texts = ['이거 정말 잼따. ', '아니 무슨 이딴게 다있냐;;','ㅋ']

#문자열이 아닌게 있는지 확인
for i in test_texts:
    if type(i)!=str:
        print(i)
        
# train 데이터 입력값(X)을 정제(Cleaning)
import re
from soynlp.normalizer import repeat_normalize

def clean_korean_text(text):
    # 특수 문자 및 숫자 제거
    text = re.sub(r'[^가-힣ㄱ-ㅎㅏ-ㅣ\s]', '', text)

    # 반복되는 자음, 모음 제거 (e.g., 'ㅋㅋㅋ' -> 'ㅋ')
    text = repeat_normalize(text, num_repeats=1)

    # 띄어쓰기 정규화 (연속된 공백 문자를 하나의 공백 문자로 변환)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

clean_test_texts=[]
for i in test_texts:
    clean_test_texts.append(clean_korean_text(i))

# 학습된 TF-IDF 벡터라이저로 테스트 데이터 변환
X_test_sample = loaded_lambda_vectorizer.transform(clean_test_texts)
X_test_sample_dense = X_test_sample.toarray()
print(X_test_sample_dense)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#불균형데이터확인
df_train[df_train.iloc[:,1]==0]  #18678 
df_train[df_train.iloc[:,1]==1]  #18822
df_train.shape

(25000, 2)

In [ ]:
import numpy as np
X_train_dense = np.expand_dims( X.toarray(), axis=-1 )
# X_train_dense.shape
# X.shape[1]
# X.toarray().shape[1]

35800

In [ ]:
#DNN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization , Input, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    # input_layer,
    Input(shape=(X_train_dense.shape[1],)),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.6),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.6),
    Dense(1, activation='sigmoid')
])

# 모델 컴파일 및 학습
optimizer= Adam(learning_rate=0.002)
model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

# 콜백 정의
early_stopping = EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)

# model.fit(X.toarray(), y, epochs = 10, batch_size = 500, validation_split=0.2)  #0.8417
model.fit(
    X.toarray(), y, 
    epochs = 20, batch_size = 50, 
    validation_split=0.3,
    callbacks=[early_stopping]
    ) 

#Okt()토크나이저를 넣지 않았을 때
# loss: 0.1659 - accuracy: 0.9387 - val_loss: 0.5841 - val_accuracy: 0.7403
#okt() 토크나이저를 썼을 때
# loss: 0.1598 - accuracy: 0.9409 - val_loss: 0.5469 - val_accuracy: 0.8003


Epoch 1/20
350/350 [==============================] - 18s 46ms/step - loss: 0.6051 - accuracy: 0.6861 - val_loss: 0.5580 - val_accuracy: 0.8011
Epoch 2/20
350/350 [==============================] - 15s 41ms/step - loss: 0.3765 - accuracy: 0.8358 - val_loss: 0.4189 - val_accuracy: 0.8019
Epoch 3/20
350/350 [==============================] - 14s 40ms/step - loss: 0.2565 - accuracy: 0.8977 - val_loss: 0.4598 - val_accuracy: 0.8052
Epoch 4/20
350/350 [==============================] - 14s 40ms/step - loss: 0.1975 - accuracy: 0.9254 - val_loss: 0.5203 - val_accuracy: 0.7955
Epoch 5/20
350/350 [==============================] - 15s 42ms/step - loss: 0.1598 - accuracy: 0.9409 - val_loss: 0.5469 - val_accuracy: 0.8003


In [ ]:
# model.save('3_31_DNN 튜닝모델.h5')

In [ ]:
test_texts = ['이거 정말 잼따. ', '아니 무슨 이딴게 다있냐;;','ㅋ']

#문자열이 아닌게 있는지 확인
for i in test_texts:
    if type(i)!=str:
        print(i)
        
# train 데이터 입력값(X)을 정제(Cleaning)
import re
from soynlp.normalizer import repeat_normalize

def clean_korean_text(text):
    # 특수 문자 및 숫자 제거
    text = re.sub(r'[^가-힣ㄱ-ㅎㅏ-ㅣ\s]', '', text)

    # 반복되는 자음, 모음 제거 (e.g., 'ㅋㅋㅋ' -> 'ㅋ')
    text = repeat_normalize(text, num_repeats=1)

    # 띄어쓰기 정규화 (연속된 공백 문자를 하나의 공백 문자로 변환)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

clean_test_texts=[]
for i in test_texts:
    clean_test_texts.append(clean_korean_text(i))

# 학습된 TF-IDF 벡터라이저로 테스트 데이터 변환
X_test_sample = vectorizer.transform(clean_test_texts)
X_test_sample_dense = X_test_sample.toarray()

# 모델을 사용하여 예측 수행
predictions = model.predict(X_test_sample_dense)
print(predictions)

# 예측 결과 출력 (긍정: 1, 부정: 0)
print("예측 결과:", np.round( predictions ).astype(int))

1/1 [==============================] - 0s 33ms/step
[[0.7537623 ]
 [0.02477952]
 [0.65656054]]
예측 결과: [[1]
 [0]
 [1]]


닉네임기준으로 
카톡대화내용을 기준으로 테스트 문장을 여러개 불러와서 예측 후 그 값의 비율을 계산 출력해준다.

In [ ]:
# 카톡대화 불러와서 정제,(정규화코드)하는 함수
import re

def get_from_txt(txt):
    data= open(txt,"r", encoding='utf-8').read().split('\n')
    sentences=[]
    for line in data:
        pattern = r'\[(.*?)\]\s+\[(.*?)\]\s+(.+)'
        match = re.match(pattern, line)
        if match:
            name = match.group(1)  # 첫 번째 대괄호 안의 단어 추출
            time = match.group(2)  # 두 번째 대괄호 안의 단어 추출
            content = match.group(3)  # 대괄호 뒤의 내용 추출
            # print(name, time, content)
            temp=[name,time,content]
            sentences.append(temp)    
    return sentences

#함수확인
get_from_txt('sample.txt')

In [ ]:
#닉네임 입력단 
target_name = str(input())
print(target_name)  #김하영 입력

김하영


In [ ]:
# 저장된 모델 불러오기
# from tensorflow.keras.models import load_models
# model= load_models('3_31_DNN 튜닝모델.h5')


#입력된 이름의 '대화내역만' 담기
received_texts= []
for i in get_from_txt('sample.txt'): 
    if i[0] == target_name:
        received_texts.append( i[2] )
        
# 이모티콘, 사진, 샵검색 제거 
clean1_received_texts = []
for i in received_texts:
    if '샵검색:' not in i: 
        if "이모티콘" not in i:
            if '샵검색:' not in i:
                clean1_received_texts.append(str(i))

#=========== 이쯤에서 답장시간 계산기 구현   =======================
          
          
#텍스트 정제  
clean2_received_texts= [clean_korean_text(i) for i in clean1_received_texts]

# # 학습된 TF-IDF 벡터라이저로 테스트 데이터 변환
X_received_texts = vectorizer.transform(clean2_received_texts)
X_received_texts_dense = X_received_texts.toarray()


# # 모델을 사용하여 예측 수행
predictions = np.round(model.predict(X_received_texts_dense))
#예측 결과 출력 (긍정: 1, 부정: 0)
print(predictions.squeeze().tolist()) #차원을 축소하고 리스트객체로 변환

cnt0=0;cnt1=0
for i in predictions.squeeze().tolist():
    if int(i)==0:
        cnt0+=1
    else:
        cnt1+=1

#부정과 긍정문의 갯수
print('부정문과 긍정문의 갯수:',cnt0,cnt1)

#긍정과 부정의 비율( 긍정문의 수 / 부정문의 수)
print('긍정과 부정의 비율: ',cnt1/cnt0)
#숫자가 1이상이고 높을수록 긍정적이다.



6/6 [==============================] - 0s 5ms/step
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]
부정문과 긍정문의 갯수: 87 88
긍정과 부정의 비율:  1.0114942528735633
